events {}
http {
    upstream ml_service {
        # Трафик идет на GREEN-сервис (v1.1.0)
        server ml-service-green:8080; 
    }
    
    server {
        listen 80;
        
        location / {
            proxy_pass http://ml_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
